// Package docs Code generated by swaggo/swag at 2025-07-13 01:02:00.977086 +0200 CEST m=+0.803808376. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/evaluate": {
            "post": {
                "description": "Evaluates a transaction on the Hyperledger Fabric network without committing it",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Evaluate a chaincode transaction",
                "parameters": [
                    {
                        "description": "Transaction Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    }
                }
            }
        },
        "/api/invoke": {
            "post": {
                "description": "Invokes a transaction on the Hyperledger Fabric network",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Invoke a chaincode transaction",
                "parameters": [
                    {
                        "description": "Transaction Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.TransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "get": {
                "description": "Reloads chaincode metadata and updates dynamic endpoints for all chaincodes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Refresh chaincode metadata and dynamic endpoints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.TransactionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.TransactionRequest": {
            "description": "Transaction request structure for invoking or evaluating chaincode",
            "type": "object",
            "properties": {
                "args": {
                    "description": "Arguments to pass to the chaincode function",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[]"
                    ]
                },
                "chaincode_name": {
                    "description": "Name of the chaincode to invoke",
                    "type": "string",
                    "example": "mycc"
                },
                "function": {
                    "description": "Function name to call in the chaincode",
                    "type": "string",
                    "example": "GetAllAssets"
                }
            }
        },
        "api.TransactionResponse": {
            "description": "Response structure for chaincode transactions",
            "type": "object",
            "properties": {
                "block_number": {
                    "description": "Block number where the transaction was committed",
                    "type": "integer",
                    "example": 123
                },
                "error": {
                    "description": "Error message (if failed)",
                    "type": "string",
                    "example": "Invalid arguments"
                },
                "result": {
                    "description": "Result of the transaction (if successful)",
                    "type": "string",
                    "example": "{\"key\":\"value\"}"
                },
                "result_code": {
                    "description": "Result code from the chaincode",
                    "type": "integer",
                    "example": 200
                },
                "status": {
                    "description": "Status of the transaction (\"success\" or \"error\")",
                    "type": "string",
                    "example": "success"
                },
                "success": {
                    "description": "Whether the transaction was successful",
                    "type": "boolean",
                    "example": true
                },
                "tx_id": {
                    "description": "Transaction ID",
                    "type": "string",
                    "example": "tx123"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Hyperledger Fabric API",
	Description:      "API for interacting with Hyperledger Fabric network.\u003cbr/\u003e\u003cbr/\u003eAvailable chaincodes:\u003cbr/\u003e\u003ca href=\"/swagger/demochainlaunch.json\"\u003edemochainlaunch\u003c/a\u003e ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
